### ISSUE TITLE
Messy Code

### ISSUE THREAD

**Issue by ListenXunInNight** [PerfectlySoft/Perfect-SMTP#16]
In PerfectSMTP.swift at 326 lines. 
(body += "Subject: =?UTF-8?Q?\(subject)?=\r\n")

It may cause messy code when the email SUBJECT is Chinese.

Change this line into  (body += "Subject: =?UTF-8?B?\(subject.base64Encoded())?=\r\n") can solve this problem.

**Comment by RockfordWei** [comment]
sorry about this very late reply. could you please PR & test it? Thank you.

**Comment by ListenXunInNight** [comment]
E, this problem has been solved in some months ago.
